#ifndef WR_TEXTURE_H
#define WR_TEXTURE_H

#include <stdbool.h>
#include <raylib.h>

typedef enum {
    WR_TEXTURE_NONE = 0,

    WR_TEXTURE_BRICK_1,
    WR_TEXTURE_BRICK_2,
    WR_TEXTURE_BRICK_3,
    WR_TEXTURE_BRICK_4,
    WR_TEXTURE_BRICK_5,
    WR_TEXTURE_BRICK_6,
    WR_TEXTURE_BRICK_7,
    WR_TEXTURE_BRICK_8,

    WR_TEXTURE_CURSED_1,
    WR_TEXTURE_CURSED_2,
    WR_TEXTURE_CURSED_3,
    WR_TEXTURE_CURSED_4,
    WR_TEXTURE_CURSED_5,
    WR_TEXTURE_CURSED_6,

    WR_TEXTURE_DOORS_1,
    WR_TEXTURE_DOORS_2,
    WR_TEXTURE_DOORS_3,
    WR_TEXTURE_DOORS_4,
    WR_TEXTURE_DOORS_5,
    WR_TEXTURE_DOORS_6,
    WR_TEXTURE_DOORS_7,
    WR_TEXTURE_DOORS_8,
    WR_TEXTURE_DOORS_9,
    WR_TEXTURE_DOORS_10,

    WR_TEXTURE_SCENERY_1,
    WR_TEXTURE_SCENERY_2,

    WR_TEXTURE_STONE_1,
    WR_TEXTURE_STONE_2,
    WR_TEXTURE_STONE_3,
    WR_TEXTURE_STONE_4,
    WR_TEXTURE_STONE_5,
    WR_TEXTURE_STONE_6,
    WR_TEXTURE_STONE_7,
    WR_TEXTURE_STONE_8,
    WR_TEXTURE_STONE_9,
    WR_TEXTURE_STONE_10,
    WR_TEXTURE_STONE_11,

    WR_TEXTURE_TILES_1,
    WR_TEXTURE_TILES_2,
    WR_TEXTURE_TILES_3,
    WR_TEXTURE_TILES_4,
    WR_TEXTURE_TILES_5,
    WR_TEXTURE_TILES_6,
    WR_TEXTURE_TILES_7,
    WR_TEXTURE_TILES_8,
    WR_TEXTURE_TILES_9,
    WR_TEXTURE_TILES_10,
    WR_TEXTURE_TILES_11,

    WR_TEXTURE_WOOD_1,
    WR_TEXTURE_WOOD_2,
    WR_TEXTURE_WOOD_3,
    WR_TEXTURE_WOOD_4,

    WR_TEXTURE_COUNT
} WrTextureType;

typedef struct WrTexture {
    int width;
    int height;
    Color* data;
} WrTexture;

void InitTextures(WrTexture* textures);
void TerminateTextures(WrTexture* textures);

const WrTexture* GetTexture(const WrTexture* textures, int id);

#endif // WR_TEXTURE_H
