#ifndef WR_CONSTANTS_H
#define WR_CONSTANTS_H

#define WR_PI 3.1415927f

#define WR_DEFAULT_SCREEN_WIDTH 1600
#define WR_DEFAULT_SCREEN_HEIGHT 1600

#define WR_MAP_CELL_SIZE 64
#define WR_MAP_CELL_COLLISION_RADIUS (WR_MAP_CELL_SIZE / 4)

#define WR_PLAYER_START_POSITION_X 300.f
#define WR_PLAYER_START_POSITION_Y 300.f
#define WR_PLAYER_START_DIRECTION_X 0.f
#define WR_PLAYER_START_DIRECTION_Y 1.f
#define WR_PLAYER_MOVE_DELTA 3.f
#define WR_PLAYER_TURN_DELTA 0.2f
#define WR_PLAYER_FOV (WR_PI / 3.f)

#endif // WR_CONSTANTS_H