#ifndef WR_CONSTANTS_H
#define WR_CONSTANTS_H

#define WR_SCREEN_DEFAULT_WIDTH 1200
#define WR_SCREEN_DEFAULT_HEIGHT 800

#define WR_PLAYER_FOV 60.f
#define WR_PLAYER_MOVE_SPEED 3.f
#define WR_PLAYER_TURN_SPEED 3.f

#endif // WR_CONSTANTS_H