#ifndef __WOLFENSTEIN_RAYCASTER_MACROS_
#define __WOLFENSTEIN_RAYCASTER_MACROS_

#define PI 3.1415926535

#define DISPLAY_WIDTH 1024
#define DISPLAY_HEIGHT 1024

#define MINIMAP_WIDTH_RATIO 0.25f
#define MINIMAP_HEIGHT_RATIO 0.25f

#define CELL_SIZE 64

#define PLAYER_SIZE 8
#define PLAYER_MOVE_DELTA 1.0f
#define PLAYER_ANGLE_DELTA 0.05f
#define PLAYER_VIEW_ANGLE (PI / 3.0)

#endif // __WOLFENSTEIN_RAYCASTER_MACROS_